import raw from "./project-presentation.json";

// Generated by scripts/build_project_presentation_data.py from real repo
// artifacts (results/final/v2, experiments/E*, docs/*). Do not
// hand-edit — re-run the builder script instead. Types are inferred from the
// JSON literal by TypeScript (resolveJsonModule), so this stays in sync with
// the generator automatically.
export const presentation = raw;

export type ProvenanceSource = {
  experimentId: string;
  sourcePath: string;
  population: string;
  measured: string;
  note?: string;
};

export type Metric = {
  value: number | string;
  unit: string;
} & ProvenanceSource;
